

#' Read EMOTE data from a ZIP archive containing multiple EmoteConv output directories
#' @param zip.file filename of the ZIP archive to load. The ZIP archive may contain multiple directories generated by EmoteConv.
#' @param ambig a logical specifying weither to load ambiguous or unambiguously counts
#' @return a SummarizedExperiment object with two assays "N" and "Q" respectively storing raw counts and quantitative values.
#'         Seqnames store path of the file the value.
#' @export
#' @import IRanges
#' @import GenomicRanges
#' @author Julien Prados
EMOTE_readConvOutput <- function(zip.file,ambig=FALSE) {

  # Extract filenames to load from zip archives
  zip.filelist <- unzip(zip.file,list=TRUE)$Name
  zip.filelist <- zip.filelist[!grepl("^\\.",basename(zip.filelist))]
  pos.file <- grep("UnambPosTable.csv$",zip.filelist,value=TRUE,ignore.case=TRUE)
  neg.file <- grep("UnambNegTable.csv$",zip.filelist,value=TRUE,ignore.case=TRUE)
  if (ambig) {
    pos.file <- setdiff(grep("AmbPosTable.csv$",zip.filelist,value=TRUE,ignore.case=TRUE),pos.file)
    neg.file <- setdiff(grep("AmbNegTable.csv$",zip.filelist,value=TRUE,ignore.case=TRUE),neg.file)
  }
  ss.file <- grep("EmoteBarcode(s?)Report.(txt|csv)$",zip.filelist,value=TRUE,ignore.case=TRUE)

  # Load sample sheets from zip archive
  read.sample.sheet.from.zip <- function(f) {
    txt <- readLines(unz(zip.file,f))
    txt <- txt[grep("^(Emote_Barcode|D6[A-Z])\t",txt)]
    sample_sheet <- read.table(text=txt,sep="\t",header=TRUE,stringsAsFactors=FALSE,check.names=FALSE,quote='"',row.names="Emote_Barcode",comment="")
    names(sample_sheet)[names(sample_sheet)=="Total emote barcode reads"] <- "Total_emote_barcode_reads"
    names(sample_sheet)[names(sample_sheet)=="Unmapped Reads"] <- "Unmapped_reads"
    sample_sheet <- sample_sheet[c("Total_emote_barcode_reads","Unmapped_reads")]
    sample_sheet
  }
  cat("loading",ss.file,"...\n")
  sample_sheet <- lapply(ss.file,read.sample.sheet.from.zip)
  sample_sheet <- setNames(sample_sheet,dirname(ss.file))
  bc <- sapply(sample_sheet,"rownames")
  if (!all(bc==bc[,1])) stop("barcodes not synchronised in all sample sheets")
  sample_sheet <- cbind(
    Total_emote_barcode_reads=rowSums(sapply(sample_sheet,'[[',"Total_emote_barcode_reads")),
    Unmapped_reads=rowSums(sapply(sample_sheet,'[[',"Unmapped_reads"))
  )
  rownames(sample_sheet) <- bc[,1]

  # Load EMOTE tables from ZIP archive
  read.emote.table.from.zip <- function(f) read.table(unz(zip.file,f),sep="\t",header=TRUE,stringsAsFactors=FALSE,check.names=FALSE,quote='"',fill=TRUE,comment="")
  cat("loading",pos.file,"...\n")
  pos <- setNames(lapply(pos.file,read.emote.table.from.zip),dirname(pos.file))
  pos <- stack(SplitDataFrameList(pos),"path")

  cat("loading",neg.file,"...\n")
  neg <- setNames(lapply(neg.file,read.emote.table.from.zip),dirname(neg.file))
  neg <- stack(SplitDataFrameList(neg),"path")


  x <- rbind(pos,neg)
  Q <- as.matrix(x[grep("^D6.+_Q$",names(x),value=TRUE)])
  colnames(Q) <- sub("_Q","",colnames(Q))
  N <- as.matrix(x[colnames(Q)])
  E <- SummarizedExperiment(
    SimpleList(N=N,Q=Q),
    rowRanges=GRanges(x$path,IRanges(x$Genomic_pos,width=1),strand=unname(c(plus="+",minus="-")[x$Strand]),nuc5p=RNAStringSet(x$X5._base))
  )

  sample_sheet <- sample_sheet[match(colnames(E),rownames(sample_sheet)),,drop=FALSE]
  rownames(sample_sheet) <- colnames(E)
  colData(E) <- DataFrame(sample_sheet)

  return(E)
}






